#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
argv=("$@")
cmd=$(scp -o StrictHostKeyChecking=no ${argv[0]} ${argv[2]}@${argv[1]}:~/)
if [ $# -eq 4 ]; then
    echo "$cmd"
else
    echo " Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

