#!/usr/bin/env bash
# Redirect and start against
apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sed -i "/listen 80 default_server;/c\ \tlisten 80 default_server;\n \trewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" default
service nginx restart
