#!/usr/bin/env bash
#Nginx likes port 80 
sed -i 's/listen \[\:\:\]:80 default_server ipv6only\=on;/listen [::]1:80 default_server ipv6only=on;/' /etc/nginx/sites-enabled/default 
service nginx restart
