#!/usr/bin/env bash
#This script display Best School 10 times.
#in the 9th iteration display Hi.


i=1
str="Best School"
while [ $i -lt 11 ]; do
if [ $i -ne 9 ]; then
    echo "$str"
else
    echo "Hi"
fi
((i=i+1))
done