#!/usr/bin/env bash
#This script display Best School 10 times.
#in the 9th iteration display Hi.


i=0
str="Best School"
while [ $i -lt 10 ]; do
if [ $i -eq 9 ]; then
    
    echo "Hi"
fi
echo "$str"
((i=i+1))
done