#!/usr/bin/env bash
#This Bash script that displays:
#he content of the current directory
#In a list format
#Where only the part of the name after
#the first dash is displayed (refer to the example).


dir=$(ls)
for i in $dir; do
    echo "$i" | cut -d '-' -f2
done