#!/usr/bin/env bash
#This is a Bash script
#that gives you information about the school file.

file=school
count=0
if [ -e "$file" ]; then
    echo "$file file exists"
    count=1
else
    echo "$file file does not exist"
fi
if [ "$count" -eq 1 ]; then
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi
fi
if [ "$count" -eq 1 ]; then
    if [ -f $file ]; then
        echo "$file is a regular file"
    fi
fi