#!/usr/bin/env bash
#Configure ufw so that it blocks all incoming traffic,
#except the following TCP ports:, 22 (SSH), 443 (HTTPS SSL) and 80 (HTTP).
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoin
sudo ufw allow OpenSSH
sudo ufw allow https
sudo ufw allow http
