#!/usr/bin/env bash
#Script to apache server listen port 8080
service apache2 start
sed -i "/*:80>/c\<VirtualHost *:8080>" /etc/apache2/sites-enabled/000-default.conf
sed -i "/Listen 80/c\Listen 8080" /etc/apache2/ports.conf
service apache2 restart
